<a href="https://colab.research.google.com/github/prashanthRanapangu/python-course-work/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

print(np.dot(A, B))
print(np.linalg.det(A))
print(np.linalg.inv(A))
eigenvalues, eigenvectors=np.linalg.eig(A)
print(eigenvalues)
print(eigenvalues)
C=np.array([5,11])
solution=np.linalg.solve(A,C)
print(solution)

[[19 22]
 [43 50]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[-0.37228132  5.37228132]
[-0.37228132  5.37228132]
[1. 2.]


In [13]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
#Stacking array vertically and horizontally
vertical_stack=np.vstack((A,B))
horizontal_stack=np.hstack((A,B))
print(vertical_stack)
print(horizontal_stack)
split_arr=np.split(np.array([1,2,3,4,5,6]),2)
print(split_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[array([1, 2, 3]), array([4, 5, 6])]


In [18]:
import pandas as pd

product_prices=pd.Series([2999,15999,5299,4999,1999],
                         index=["wireless Earbuds","Smartphone","Laptop","Smartwatch","Bluetooth Speaker"])
print(product_prices)
print("min:",product_prices.min())
print("max:",product_prices.max())
print("head :",product_prices.head(2))
print("tail:",product_prices.tail(3))

wireless Earbuds      2999
Smartphone           15999
Laptop                5299
Smartwatch            4999
Bluetooth Speaker     1999
dtype: int64
min: 1999
max: 15999
head : wireless Earbuds     2999
Smartphone          15999
dtype: int64
tail: Laptop               5299
Smartwatch           4999
Bluetooth Speaker    1999
dtype: int64


In [19]:
print("apply (Adding 18% GST):\n",product_prices.apply(lambda x:x+10))


apply (Adding 18% GST):
 wireless Earbuds      3009
Smartphone           16009
Laptop                5309
Smartwatch            5009
Bluetooth Speaker     2009
dtype: int64


In [20]:
print("map(formatting as currency ):\n",product_prices.map(lambda x:f"${x}"))

map(formatting as currency ):
 wireless Earbuds      $2999
Smartphone           $15999
Laptop                $5299
Smartwatch            $4999
Bluetooth Speaker     $1999
dtype: object


In [21]:
print("sort by values:\n",product_prices.sort_values())

sort by values:
 Bluetooth Speaker     1999
wireless Earbuds      2999
Smartwatch            4999
Laptop                5299
Smartphone           15999
dtype: int64


In [24]:
print("sort by values:\n",product_prices.sort_values(ascending=False))

sort by values:
 Smartphone           15999
Laptop                5299
Smartwatch            4999
wireless Earbuds      2999
Bluetooth Speaker     1999
dtype: int64


In [25]:
print("Values Counts:\n", product_prices.value_counts())

Values Counts:
 2999     1
15999    1
5299     1
4999     1
1999     1
Name: count, dtype: int64
